[application]
name = "dioxus-status"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Dioxus Status"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
